name: Scrape today’s death count, tweet about it, and generate a license plate
on:
  push:
  schedule:
    - cron: '0 19 * * *' # FIXME 13h CST, how to deal with DST… eventually :/
jobs:
  store-deaths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - run: yarn install
      - run: node index.js
      - name: Store deaths data
        uses: actions/upload-artifact@v2
        with:
          name: deaths
          path: deaths.json
  tweet:
    if: ${{ github.event_name == 'schedule' }}
    needs: store-deaths
    runs-on: ubuntu-latest
    steps:
      - name: Fetch deaths data
        uses: actions/download-artifact@v2
        with:
          name: deaths
      - name: Construct tweet
        run: echo "TWEET_TEXT='As of $(jq -r .dateString deaths.json), $(jq -r .deaths deaths.json) are dead in Manitoba.'" >> $GITHUB_ENV
      - uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ env.TWEET_TEXT }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  generate-license-plate:
    needs: store-deaths
    runs-on: macos-latest
    steps:
      - name: Install ImageMagick
        run: brew install imagemagick
      - uses: actions/checkout@v1
      - name: Fetch deaths data
        uses: actions/download-artifact@v2
        with:
          name: deaths
      - name: Generate license plate
        run: ./generate-license.sh
      - name: Store generated license plate
        uses: actions/upload-artifact@v2
        with:
          name: license-plate
          path: generated-license*.jpeg
