name: Scrape today’s death count, tweet about it, and generate a license plate
on:
  schedule:
    - cron: '0 19 * * *' # FIXME 13h CST, how to deal with DST… eventually :/
jobs:
  store-deaths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - run: yarn install
      - run: node index.js
      - name: Store deaths data
        uses: actions/upload-artifact@v2
        with:
          name: deaths
          path: deaths.json
  tweet:
    needs: store-deaths
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - name: Fetch deaths data
        uses: actions/download-artifact@v2
        with:
          name: deaths
      - name: Construct tweet
        run: echo "TWEET_TEXT=$(node construct-tweet.js)" >> $GITHUB_ENV
      - uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ env.TWEET_TEXT }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      - uses: EndBug/add-and-commit@v5
        with:
          add: 'tweet-templates.txt'
          author_name: Github Action as Buck
          author_email: b@chromatin.ca
          message: 'Update tweet queue'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
  generate-license-plate:
    needs: store-deaths
    runs-on: macos-11.0
    steps:
      - name: Install ImageMagick
        run: brew install imagemagick
      - uses: actions/checkout@v1
      - name: Fetch deaths data
        uses: actions/download-artifact@v2
        with:
          name: deaths
      - name: Generate license plate
        run: ./generate-license.sh
      - name: Store generated license plate
        uses: actions/upload-artifact@v2
        with:
          name: license-plate
          path: "generated-*.jpg"
  upload-license-to-drive:
    needs: generate-license-plate
    runs-on: ubuntu-latest
    steps:
      - name: Fetch license plate
        uses: actions/download-artifact@v2
        with:
          name: license-plate
      - name: rclone
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: "copy generated-*.jpg BriansRetire:"
