name: Send a Tweet
on:
  push:
  schedule:
    - cron: '* 13 * * *'
jobs:
  store-deaths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - run: yarn install
      - run: node index.js
      - name: Store deaths data
        uses: actions/upload-artifact@v2
        with:
          name: deaths
          path: deaths.json
  tweet:
    needs: store-deaths
    runs-on: ubuntu-latest
    steps:
      - name: Fetch deaths data
        uses: actions/download-artifact@v2
        with:
          name: deaths
      - name: Construct tweet
        run: echo "TWEET_TEXT=$(jq .deaths deaths.json)" >> $GITHUB_ENV
      - uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ env.TWEET_TEXT }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
